### ISSUE TITLE
Implement VPC Interface Endpoint for SSM support

### ISSUE THREAD

**Issue by tonpatel** [coveo/spring-boot-parameter-store-integration#2]
It's a good useful library for Lambda to SSM integration.
We've a VPC without internet access. We access SSM via VPC EndPoint.
could you please implement the support for VPC Endpoint?

Thanks a lot!

**Comment by fredboutin** [comment]
AWS Lambda supports VPC, here is how to set it up: https://docs.aws.amazon.com/lambda/latest/dg/vpc.html

**Comment by tonpatel** [comment]
Thank you for your quick reply!
VPC - no internet connection; SSM Interface VPC Endpoint; VPC DNS Hostnames disabled
I can not use the default SSM url. 

ParameterStorePropertySourceEnvironmentPostProcessor.postProcessEnvironment()
Instead of AWSSimpleSystemsManagementClientBuilder.defaultClient() default client.

can we also implement to connect to a different serviceEndpoint? Please see if we can add setEndpointConfiguration code or let me know if you have other suggestion.

if (environment.getProperty(PARAMETER_STORE_SSM_VPC_ENDPOINT_CONFIGURATION_PROPERTY) != null) {
                builder.setEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(environment.getProperty(PARAMETER_STORE_SSM_VPC_ENDPOINT_CONFIGURATION_PROPERTY),
                                                                                            System.getenv(AWS_DEFAULT_REGION)));
            }

**Comment by fredboutin** [comment]
I assumed that the default client was detecting the VPC and using the VPC endpoint, but you seem to be right it uses the generic endpoint https://ssm.us-east-1.amazonaws.com. I'll take a look because we'll want to use that too. Thanks for pointing that out!

**Comment by fredboutin** [comment]
@tonpatel you can take a look at the PR, it does pretty much what you said with little changes.

**Comment by tonpatel** [comment]
Thank you very much! It's a nice feature!
